
import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  uz: {
    title: "Oshxona Malikasi",
    subtitle: "Sizning aqlli oshpazlik yordamchingiz",
    scanNow: "Mahsulotlarni skanerlash",
    detectedIngredients: "Aniqlangan mahsulotlar",
    generateRecipe: "Retsept yaratish",
    processing: "Tahlil qilinmoqda...",
    nutritionInfo: "Ozuqaviy qiymati",
    recipes: "Tavsiya etilgan retseptlar",
    switchLang: "Tilni o'zgartirish",
    calories: "Kaloriya",
    protein: "Oqsil",
    carbs: "Uglevod",
    fats: "Yog'lar",
    ingredientsLabel: "Kerakli masalliqlar",
    instructionsLabel: "Tayyorlash usuli",
    dietaryFilters: "Parhez cheklovlari",
    culturalHint: "O'zbek milliy taomlari filtri faol",
    voicePrompt: "Ovozingiz bilan buyruq bering",
    saveRecipe: "Saqlash",
    saved: "Saqlangan",
    myCookbook: "Mening kitobim"
  },
  en: {
    title: "Kitchen Queen",
    subtitle: "Your Smart Culinary Assistant",
    scanNow: "Scan Ingredients",
    detectedIngredients: "Detected Ingredients",
    generateRecipe: "Generate Recipe",
    processing: "Processing...",
    nutritionInfo: "Nutritional Facts",
    recipes: "Recommended Recipes",
    switchLang: "Switch Language",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fats: "Fats",
    ingredientsLabel: "Ingredients Needed",
    instructionsLabel: "Instructions",
    dietaryFilters: "Dietary Filters",
    culturalHint: "Cultural preferences enabled",
    voicePrompt: "Give a voice command",
    saveRecipe: "Save",
    saved: "Saved",
    myCookbook: "My Cookbook"
  },
  ru: {
    title: "Королева Кухни",
    subtitle: "Ваш умный кулинарный помощник",
    scanNow: "Сканировать продукты",
    detectedIngredients: "Обнаруженные ингредиенты",
    generateRecipe: "Создать рецепт",
    processing: "Обработка...",
    nutritionInfo: "Пищевая ценность",
    recipes: "Рекомендованные рецепты",
    switchLang: "Сменить язык",
    calories: "Калории",
    protein: "Белки",
    carbs: "Углеводы",
    fats: "Жиры",
    ingredientsLabel: "Необходимые ингредиенты",
    instructionsLabel: "Инструкции",
    dietaryFilters: "Диетические фильтры",
    culturalHint: "Культурные предпочтения включены",
    voicePrompt: "Дайте голосовую команду",
    saveRecipe: "Сохранить",
    saved: "Сохранено",
    myCookbook: "Моя книга"
  }
};